# 製品設定

---
- name: スマートフォン
  price: 89800
  stock: 120
  id: f47ac10b-58cc-4372-a567-0e02b2c3d479
  features:
    - カメラ
    - GPS
    - 顔認証

---
- name: ラップトップ
  price: 125000
  stock: 50
  id: 550e8400-e29b-41d4-a716-446655440001
  features:
    - 高性能 CPU
    - 16GB RAM
    - SSD ストレージ

---
- name: タブレット
  price: 58000
  stock: 75
  id: 6ba7b810-9dad-11d1-80b4-00c04fd430c9
  features:
    - タッチスクリーン
    - スタイラスペン対応
    - 長時間バッテリー
